name = "lumin/debugger"
version = "0.5.0"
description = "A customizable and extendable debugger for open source software"
authors = ["2jammers"]
repository = "https://github.com/luminlabsdev/debugger"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
