name = "lumin/debugger"
version = "1.0.0"
description = "A customizable and extendable debugger for open source software"
authors = ["jmesrje"]
repository = "https://github.com/lumin-org/debugger"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src",
]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.0.2", target = "lune" }
selene = { name = "pesde/selene", version = "^0.27.1", target = "lune" }

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
