name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    changelog:
        name: Changelog
        runs-on: ubuntu-latest
        outputs:
          release-body: ${{ steps.update-changelog.outputs.release-notes }}
        steps:
          - uses: actions/checkout@v4
            with:
              ref: main

          - name: Update changelog
            id: update-changelog
            uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
            with:
              tag: ${{ github.ref_name }}
              changelogPath: 'docs/changelog.md'

          - name: Commit and push
            uses: EndBug/add-and-commit@v9
            with:
              message: Bump version to ${{ github.ref_name }}
              default_author: github_actions

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: changelog
        steps:
          - uses: actions/checkout@v4

          - name: Setup Pesde
            uses: 2jammers/setup-pesde@v0.3.0
            with:
              cache: true

          - name: Install dependencies
            run: pesde install

          - name: Format code
            run: stylua src/

          - name: Standalone build
            run: rojo build standalone.project.json --output ./Standalone.rbxm

          - name: Standalone release
            uses: softprops/action-gh-release@v2.0.9
            with:
              tag_name: ${{ github.ref_name }}
              name: ${{ github.ref_name }}
              prerelease: ${{ contains(github.ref_name, 'rc') }}
              generate_release_notes: true
              body: |
                ## Changelog
                ${{ needs.changelog.outputs.release-body }}
              files: |
                ./Standalone.rbxm

    package:
        name: Package
        runs-on: ubuntu-latest
        needs: changelog
        steps:
        - uses: actions/checkout@v4

        - name: Setup Pesde
          uses: 2jammers/setup-pesde@v0.3.0
          with:
            cache: true
            token: '${{ secrets.PESDE_TOKEN }}'

        - name: Publish
          run: |
            pesde install
            pesde publish -y
